### PR TITLE
Active Pictorial Structures - Cost functions computation

### PR DESCRIPTION
**Pull request by nontas**
This PR does the following:

#### 1. Active Pictorial Structures
Adds (at last) an implementation of Active Pictorial Structures (APS), as proposed in:

> E. Antonakos, J. Alabort-i-Medina, S. Zafeiriou. *Active Pictorial Structures*. CVPR 2015.

Both `Inverse` and `Forward` algorithms are defined. Note that this implementation is better defined than the model presented in the original paper, because it adds a weight between the appearance and deformation terms of the cost function. Thus, the original cost function of Equation 19 of the original paper now becomes:
<p align="center">
  
</p>
and the Hessian calculation of Equation 20 takes the form:
<p align="center">
  
</p>

#### 2. Costs during fitting
Remember that after the changes introduced by https://github.com/menpo/menpofit/pull/83, our fitting results objects do not hold the actual model any more. Thus, the costs are actually computed during fitting. This adds an extra computational cost to the fitting process, which depending on the algorithm can be significantly high. Active Pictorial Structures is a good example. The `Inverse` optimisation is very fast, but the cost calculation is dramatically slow. This PR adds a `return_costs` argument to the `fit_from_shape` and `fit_from_bb` methods. If it is set to ``True``, then the returned fitting result object actually holds the costs values, otherwise `fitting_result.costs` is ``None``.

Note that the costs calculation only applies for certain MenpoFit models. In case `return_costs` is enabled for a model that does not support costs calculation, then a warning is raised informing the user that it is impossible to return the costs.

#### TODO
The things that remain to be done:

- [x] Run some more experiments that test the performance of APS
- [x] Add sampling mask to APS fitting

### CODE REVIEW

**Comment by patricksnape** [comment]
Well that is certainly a lot of changes. I'll have to do some checks on AAMs etc to see how it works with the costs. I assume APS is fine one you post a graph.

**Comment by nontas** [comment]
This is an APS experiment that shows a similar performance as the one reported in the paper. The result is slightly different than the one in the paper due to initialisation.

##### Training
* LFPW trainset with `'face_ibug_66'`
* `shape_graph = None`, `deformation_graph=None`
* `diagonal = 100`, `holistic_features = fast_dsift`, `scales = (0.5, 1.0)`, `patch_shape = (17, 17)`
* `use_procrustes=True`, `precision_dtype = np.float32`, `n_appearance_components = 150` 

##### Fitting
* AFW
* `Inverse`
* `n_shape = [5, 15]`, `max_iters = 20`
* Error based on 49 points normalised with the average edge length of the 66-point ground truth bounding box

result

**Comment by patricksnape** [comment]
Are we waiting on the sampling mask too?

**Comment by nontas** [comment]
Oh yeah I totally forgot about that.... I'll try and fix it during the weekend

**Comment by nontas** [comment]
Sampling is now implemented.

**Comment by patricksnape** [comment]
+1 seems fine to me

**Pull request merged**
