### PR TITLE
Fix error on fittingresult 

### PR DESCRIPTION
**Pull request by trigeorgis**
I came up on an issue while using a patched based AAM where it would crash on a TypeError exception. When using super, instead of calling directly the __init__ method of the base class, fixed the issue.

I also have a change on this branch for an AAM to not only use a PCAModel to model the texture, but rather for the user to provide a class to use. I can make a separate pull request for this, if you like.

### CODE REVIEW

**Comment by jalabort** [comment]
Why was super failing? Could you provide more details on what make it fail? This sounds strange to me...

Regarding the second part, it sounds sensible to me. Are you also planning to submit new models to `menpo`? And if so, do they play well with the current `LKAAMFitters`?

**Comment by patricksnape** [comment]
Yeah I think we should strip out the AAM model change until we get your AAMs in @jalabort. But the other change seems important. @trigeorgis could you update the PR to only contain the ``super`` changes?

**Comment by trigeorgis** [comment]
Re Joan: Super wasn't failing though. It was the direct calling of the
__init__ class that failed due to some race condition.
Re Patrick: Sure - will do that.

**Comment by jalabort** [comment]
Sorry read your message to fast! Yep we should pull this in then.

**Comment by patricksnape** [comment]
This is implemented now (passing appearance model type) and the Results have been updated by @nontas.

**Pull request closed without merging**
