### PR TITLE
Init classmethods

### PR DESCRIPTION
**Pull request by jabooth**
Following https://github.com/menpo/menpo/pull/533 this just updates menpofit to use the new style class methods.

### CODE REVIEW

**Comment by jabooth** [comment]
@jalabort so an interesting one here Joan. This PR is not failing due to it's new content (it is required so menpofit is brought in line with the new `init_` `@classmethods` in menpo), it's failing because it's the first build of menpofit since IncrementalPCA was added to menpo: https://github.com/menpo/menpo/pull/532.

As we move to eventually update menpofit with your menpofast work, is probabalistic PCA in it's current form removed from menpofit? We should probably resolve this somehow on this PR that's all.

**Comment by jalabort** [comment]
Hey @jabooth, I checked Travis and you seem to be correct. I removed the `distance_to_subspace` method from `PCAModel` and that's what's causing it to fail... I removed the `Probabilistic AAM` methods from the `MenpoFit` `flip_channels` branch because I was not sure they were correct. However they still are in the current `MenpoFit` master...

I see 2 options either add back `distance_to_subspace` to `Menpo` or remove `Probabilistic AAM` fitting methods from `MenpoFit`. 

I would favour the second option if you want to get this PR merged asap. I have been thinking of extending the package `menpo.models` for a quite long time, since this is an area in which I am quite keen to expand my knowledge, and done some work towards that which explicitly separates `PPCA` from `PCA` and that is why I believe we are better of without the `distance _to_subspace` method on `PCAModel` which is a `PPCA` concept...

**Comment by jabooth** [comment]
Thanks for that @jalabort. It does seem like option 2 is the best, and I like your idea of properly expanding menpo.models in a future release with more techniques. I'll remove probablalistic in this PR then so master is not broken, and we will do the channel flip PR hopefully today or tomorrow

**Comment by jalabort** [comment]
OK

**Pull request merged**
