### PR TITLE
WIP: Result - Documentation - Visualization

### PR DESCRIPTION
**Pull request by nontas**
This is a large (sorry about that!) PR that does the following:

* **Refactors fitting results**
  - We now have a base class `Result`, two algorithm classes (`NonParametricIterativeResult` and 
    `ParametricIterativeResult`) and two multi-scale classes (`MultiScaleNonParametricIterativeResult`
    and `MultiScaleParametricIterativeResult`).
  - The biggest difference with the structure we used to have is that **fitters are not stored in the fitting 
    result any more**. This makes our objects serializable and lightweight. Also the user can choose 
    whether to store the image as well.
  - All results know how to visualise themselves (check the `view()` and `view_iterations()` methods).
  - They also make it easy to access things like `shape_parameters`, `appearance_parameters`, 
    `costs`, and `errors`.
  - The `warped_images()` and `appearance_reconstructions()` are moved to the `fitter` objects (where 
    applicable).
  - As part of this task, I made sure that all our models with all possible optimisation combinations 
   actually work. I also made parameters checking and `__str__()` methods consistent.
* **Refactors errors**
  - There is a separate package called `error`. It clarifies the role of normalisers, error metrics and 
    object-specific errors (e.g. face).
  - It adds the area under the curve (AUC), failure rate and median absolute deviation (mad) 
    measures.
  - It also adds a method for generating a table with fitting results using `pandas` 
    (`menpofit.visualize.statistics_table()`).
* **Adds documentation to the whole menpofit project**
  - The documentation is built correctly.
  - It also adds a quite extensive user guide (with gif examples :) ).
* **Improves visualization**
  - It adds a new function that can render an image with multiple landmark groups either on the same 
    figure or in subplots mode (this should probably be moved to `menpo.visualize`).

TODO:
* [ ] Fix doc mapping to `menpo` classes (@patricksnape).
* [x] Define separate widgets for a simple results object (`Result`) and an iterative result object.
* [x] Define CLM visualization widgets.

### CODE REVIEW

**Comment by patricksnape** [comment]
Wow.

**Comment by nontas** [comment]
`menpowidgets` have been updated with respect to the changes of this PR (https://github.com/menpo/menpowidgets/pull/9), thus the two PRs should be merged simultaneously.

**Comment by patricksnape** [comment]
@nontas - can we merge this?

**Comment by nontas** [comment]
I intended to also do the change regarding the projected initial shapes of a parametric iterative result. However, maybe it is better to merge this for now (together with https://github.com/menpo/menpowidgets/pull/9) since it already includes a lot of stuff and I can work on that change on a separate branch.

Whatever you prefer.

**Comment by patricksnape** [comment]
I'm going to merge it

**Pull request merged**
