### PR TITLE
Fitter crop images

### PR DESCRIPTION
**Pull request by jalabort**
Grigoris needed this for his tracking system and I think it does make a lot of sense for `MenpoFit` to support this natively.

Basically, `Fitters` have now the ability to internally crop the input image they want to fit by means of the `kwarg` `crop_image` in their `fit` method. This `kwarg` is used internally by the fitters to crop the image so that their search is performed on this  cropped copy of the original input image. The meaning of the `kwarg` `crop_image` is the same as the `proportion` argument in the method `crop_to_landmarks_inplace` from the `Image` class in `Menpo` and, in fact, that is exactly what fitters do (call that method on the original input image).

### CODE REVIEW

**Comment by jalabort** [comment]
Are we happy with this?

**Comment by nontas** [comment]
It looks good! Maybe we should clearly state in the `crop_image` argument documentation that when a `float` gets passed in (so the cropping takes place), the image gets copied...

**Comment by jabooth** [comment]
I'm not too sure that this is a good idea. Shouldn't users be encouraged to do the crop themselves in the usual preprocessing step we recommend? 

Just to understand better - is the idea that the fitting result is still shown in the original image space? E.g. the user can provide a large image with a small ROI and the fit framework with both rescale and crop, but the user will see fitting results in the original scale. Have I got that correct?

**Comment by patricksnape** [comment]
@jabooth I think you are correct. There is still the issue of given the original image, how do we easily transfer the landmarks from the cropped image back to the original. For example, in the case of tracking videos - we want to render on the full video frame, but we probably want to fit on a cropped frame.

**Comment by jabooth** [comment]
Thanks @patricksnape. If this is the case then I can maybe get behind it - I agree, it's currently not easy for users to 'undo' a crop operation transform for instance and transfer landmarks back from a cropped image to the original. It does feel like this is a deficiency we should be looking to address in core Menpo with a general solution, but pragmatically I can see why this would be a useful option here.

I could also see this as an internal optimisation of the fit framework. Put another way, if this does just improve fitting speed and the information being cropped is of no use then why would any user not want this done? It feels somewhat similar to the initial resize we do - you *could* try and just take features on the image provided but we force users' images to be rescaled to the model because we feel it's always good to normalise the pixel scale. Playing devils advocate, is this a little similar?

**Comment by jalabort** [comment]
Yes.

And note that the fitter does this resizing itself when an image is provided so that features are computed in the same scale as they were in training. So I would say this cropping does a similar thing, it simply offers the user the possibility to limit the search area of the fitter internal algorithm to a sensible area of the image around the initial estimate. 

If the main concern is the fact that a potentially big image gets copied then we should deal with this properly and define a proper `crop` method for images so that it does not happen always `inplace`. That would solve the copy issue since the we could get a view onto crop region and simply copy this part instead of the whole image.

This little change can makes `menpofit` much more efficient that it currently is for large images and I strongly believe it is the right approach for solving this issue.

**Comment by jabooth** [comment]
summarising in-person discussions between myself @jalabort and @patricksnape - we are all in agreement that this makes sense as an addition, and maybe should be conservatively enabled by default with a very large proportion (0.5?)

**Comment by jabooth** [comment]
just discussed again with @jalabort and this is a good addition that should go in before the big refactor. +1

**Pull request merged**
