### PR TITLE
Fix for thinesplatesplines 

### PR DESCRIPTION
**Pull request by grigorisg9gr**
Fix the case that two landmark points coincide and the thinesplatesplines transform raises a Linalgerror.
Same fix as in menpo/transform/thinplatesplines.py.

### CODE REVIEW

**Comment by jabooth** [comment]
Seems sensible to me, unless there is any subtly I'm missing? +1

**Comment by jalabort** [comment]
This is indeed necessary. Maybe we could use a try and except pattern in the TPS computation in transform that contains exactly the same code...

**Comment by jalabort** [comment]
I am happy for this go in.

**Comment by jalabort** [comment]
+1

**Comment by jalabort** [comment]
+1

**Comment by jabooth** [comment]
the failing tests are due to travis not bringing down the new version of menpo, so we can get this in and fix that later. +1

**Pull request merged**
