### PR TITLE
add Python 3.6 support

### PR DESCRIPTION
**Pull request by jabooth**

### CODE REVIEW

**Comment by georgesterpu** [comment]
Is there a problem with those two files that cause the AppVeyor build to fail ?
`OSError: No meta.yaml or conda.yaml files found in C:\projects\menpofit\menpofit`

**Comment by jabooth** [comment]
@georgesterpu no it's actually just a very misleading error - the real issue here is some run time dependencies are not yet build for python 3.6. Instead of telling us that (and ideally which packages are missing of course) conda currently just displays this rather unhelpful error in this case.

@patricksnape has been working on addressing the underlying issue here, which for menpofit I believe is dlib (and hence boost)

**Comment by patricksnape** [comment]
Yeah we should raise that upstream with conda-build - it's really annoying

**Comment by yo1995** [comment]
🤔 Are there any news on upgrading to Python3? Really would like to get rid of Python2 in my environment... Thx

**Comment by patricksnape** [comment]
Done now

**Pull request closed without merging**
