### PR TITLE
Flip channels

### PR DESCRIPTION
**Pull request by jalabort**
This PR adapts `menpofit` to work with the changes that menpo/menpo#524 will bring to `menpo`.

- [x] Adapt `AAMs`
- [x] Adapt `ATMs`
- [x] Adapt `CLMs`
- [x] Adapt `SDMs`
- [x] Adapt `LucasKanade`

### CODE REVIEW

**Comment by jalabort** [comment]
This is ready to be merged on my side.

When used on top of menpo/menpo#524 some test are failing still due to numerical differences. It'd be good if somebody else could properly check this perhaps re-running a large experiment on `LFPW` and check that performance hasn't dropped...

**Comment by jalabort** [comment]
@patricksnape has found some very nasty bugs on the `gradient` feature. So the above is actually not true. He will amend this on menpo/menpo#524 and we'll take it from there. Thanks @patricksnape !

**Comment by nontas** [comment]
@patricksnape and I tested this and it looks good. It can get in after https://github.com/menpo/menpo/pull/524 gets in.
+1

**Comment by jalabort** [comment]
Yep, @jacksoncsy is been actively using this branch for a while and reported stable. After we bring menpo/menpo#524 in I will have a look at the tests (amending them if needed) and hopefully we will be able to finally merge this in.

**Pull request merged**
